#!/usr/bin/env bash
# Indefinitely writes tha "I am alive" to the file /tmp/my_process.
#   Pauses two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
