#!/usr/bin/env bash
# Displays tha contents of tha current directory in list format.
#   Only displays tha part of tha name after tha first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
